# Generated by Django 3.1.3 on 2020-11-15 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0002_auto_20201115_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
    ]
