# Generated by Django 3.1.3 on 2020-11-15 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0004_appointment_preferred_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='register',
        ),
    ]
