# Generated by Django 3.1.3 on 2020-11-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0006_appointment_preferred_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_id',
            field=models.CharField(default=2, max_length=450),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
